version: '3.11'
services:
  shot-predict-app:
    build:
      context: .
      dockerfile: shortprediction/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./shortprediction:/app
      - ./requirements.txt:/app/requirements.txt
    environment:
      - PYTHONUNBUFFERED=1
